const PROMPT_CATEGORY_NAMES: Record<string, string> = {
  IMAGE: '图片创作',
  TEXT: '文本',
  STRUCTURED: '结构化提示词',
  Landscape: '风景',
  Portrait: '人像',
  'Image Generation': '图片创作',
  Creative: '创意设计',
  Design: '设计',
  Education: '教育',
  'Health & Wellness': '健康与生活',
  'Learning & Skills': '学习与技能',
  Marketing: '营销',
  'Video Generation': '视频创作',
  'Agent Skill': 'Agent 技能',
  'Web Development': 'Web 开发',
  'Vibe Coding': 'AI 编程',
  'Journaling & Reflection': '日记与反思',
  Coding: '编程',
  'Market Analysis': '市场分析',
  'Research & Analysis': '研究与分析',
  Workflows: '工作流',
  'Academic Writing': '学术写作',
  'Charts & Infographics': '图表与信息图',
  'Products & E-commerce': '商品与电商',
  'Posters & Typography': '海报与字体设计',
  'Documents & Publishing': '文档与出版',
  'Illustration & Art': '插画与艺术',
  'Scenes & Storytelling': '场景与叙事',
  'Photography & Realism': '摄影与写实',
  'Characters & People': '角色与人物',
  'Brand & Logos': '品牌与标志',
  'Architecture & Spaces': '建筑与空间',
  'UI & Interfaces': '界面设计',
  'History & Classical Themes': '历史与古典主题',
  'Other Use Cases': '其他',
  '3d': '3D 创作',
  creative: '创意设计',
  icons: '图标设计',
  portraits: '人像',
  posters: '海报',
  thumbnails: '缩略图设计',
}

export function promptCategoryLabel(category: string): string {
  return PROMPT_CATEGORY_NAMES[category] ?? category
}
